# Generated by Django 3.2.18 on 2024-10-04 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='device_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='device_type',
            field=models.CharField(blank=True, choices=[('WEB', 'WEB'), ('SPECTRO_TV', 'SPECTRO_TV'), ('LOG_SHEET', 'LOG_SHEET'), ('MELTING_REPORT', 'MELTING_REPORT'), ('IOT', 'IOT')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id__isnull', False), models.Q(('device_id', ''), _negated=True)), fields=('device_id',), name='unique_device_id_not_null_blank'),
        ),
    ]
