# Generated by Django 3.2.25 on 2025-03-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfpasswordless', '0005_auto_20201117_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbacktoken',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
